apiVersion: apps/v1
kind: Deployment
metadata:
  name: f4i-orion-f
spec:
  replicas: 1
  selector:
    matchLabels:
      app: f4i-orion
  template:
    metadata:
      labels:
        app: f4i-orion
    spec:
      containers:
      - name: f4i-orion-f
        image: fed4iot/orion-f:latest
        ports:
        - containerPort: 27017
        - containerPort: 1026
        - containerPort: 1030
      - name: http-sidecar-f
        image: fed4iot/http-sidecar-flavour:latest
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: f4i-orion-svc
  labels:
    app: f4i-orion
spec:
  type: NodePort
  selector:
    app: f4i-orion
  ports:
  - port: 27017
    nodePort:
    name: f4i-mongo
  - port: 1026
    nodePort:
    name: f4i-orion
  - port: 1030
    nodePort:
    name: f4i-vscontroller
  - port: 80
    targetPort: 5001
    nodePort:
    name: http
