apiVersion: apps/v1
kind: Deployment
metadata:
  name: f4i-orion-f
spec:
  replicas: 1
  selector:
    matchLabels:
      app: f4i-orion
  template:
    metadata:
      labels:
        app: f4i-orion
    spec:
      containers:
      - name: f4i-orion-f
        image: fed4iot/orion-f:2.2
        ports:
        - containerPort: 27017
        - containerPort: 1026
---
apiVersion: v1
kind: Service
metadata:
  name: f4i-orion-svc
  labels:
    app: f4i-orion
spec:
  type: NodePort
  selector:
    app: f4i-orion
  ports:
  - port: 27017
    nodePort:
  - port: 1026
    nodePort:
