apiVersion: apps/v1
kind: Deployment
metadata:
  name: f4i-ngsild-orionld-f
spec:
  replicas: 1
  selector:
    matchLabels:
      app: f4i-ngsild-orionld
  template:
    metadata:
      labels:
        app: f4i-ngsild-orionld
    spec:
      containers:
      - name: ngsild-silocontroller
        image: fed4iot/ngsild-silocontroller:latest
        #imagePullPolicy: Never
      - name: f4i-ngsild-orionld-f
        image: fiware/orion-ld:latest
        ports:
        - containerPort: 1026
      - name: orionld-mongodb
        image: mongo
      - name: http-sidecar-f
        image: fed4iot/http-sidecar-flavour:latest
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: f4i-ngsild-orionld-svc
  labels:
    app: f4i-ngsild-orionld
spec:
  type: NodePort
  selector:
    app: f4i-ngsild-orionld
  ports:
  - port: 1026
    nodePort:
  - port: 80
    targetPort: 5001
    nodePort:
    name: http
