apiVersion: apps/v1
kind: Deployment
metadata:
  name: f4i-ngsild-k8scorpio-f
spec:
  replicas: 1
  selector:
    matchLabels:
      app: f4i-ngsild-k8scorpio
  template:
    metadata:
      labels:
        app: f4i-ngsild-k8scorpio
    spec:
      containers:
      - name: ngsildsilocontroller
        image: fed4iot/ngsild-silocontroller:3.0
      - name: kafkabroker
        image: wurstmeister/kafka
        env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: 127.0.0.1
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: 127.0.0.1:2181
        ports:
        - containerPort: 9092
      - name: zookeeper
        image: zookeeper
        ports:
        - containerPort: 2181
      - name: scorpio
        image: scorpiobroker/scorpio:scorpio-aaio_0.9.8
        ports:
        - containerPort: 9090
      - name: postgres
        image: mdillon/postgis
        env:
        - name: POSTGRES_DB
          value: ngb
        - name: POSTGRES_PASSWORD
          value: ngb
        - name: POSTGRES_USER
          value: ngb
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: f4i-ngsild-k8scorpio-svc
  labels:
    app: f4i-ngsild-k8scorpio
spec:
  type: NodePort
  selector:
    app: f4i-ngsild-k8scorpio
  ports:
  - port: 9090
    nodePort:
