apiVersion: apps/v1
kind: Deployment
metadata:
  name: f4i-ngsild-stellio-f
spec:
  replicas: 1
  selector:
    matchLabels:
      app: f4i-ngsild-stellio
  template:
    metadata:
      labels:
        app: f4i-ngsild-stellio
    spec:
      containers:
      - name: f4i-ngsild-stellio-f
        image: fed4iot/ngsild-stellio-f:2.2
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: f4i-ngsild-stellio-svc
  labels:
    app: f4i-ngsild-stellio
spec:
  type: NodePort
  selector:
    app: f4i-ngsild-stellio
  ports:
  - port: 9090
    nodePort:
