apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-mc-noauth
spec:
  serviceName: db-svc-mc-noauth
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: mongodb
        image: mongo:4.2.2
        ports:
        - containerPort: 27017  
---
apiVersion: v1
kind: Service
metadata:
  name: db-svc-mc-noauth
  labels:
    app: database
spec:
  type: NodePort
  ports:
  - port: 27017
    targetPort:
    nodePort:
  selector:
    app: database
