apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-mc
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  #storageClassName: slow
  nfs:
    server: 192.168.123.10
    path: '/mnt/data/master-controller'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-mc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany # Access modes for volumes is defined under Persistent Volumes
  #storageClassName: slow
  resources:
    requests:
      storage: 1Gi # volume size requested
