apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: f4i-tv-murcia-parkingsite
spec:
  selector:
    matchLabels:
      app: f4i-murcia-parkingsite
  replicas: 1
  template:
    metadata:
      labels:
        app: f4i-murcia-parkingsite
    spec:
      containers:
      - name: f4i-murcia-parkingsite
        image: fed4iot/fiware-parkingsite-tv:2.4
        ports:
        - containerPort: 1030
---
apiVersion: v1
kind: Service
metadata:
  name: f4i-tv-svc-murcia-parkingsite
  labels:
    app: f4i-murcia-parkingsite
spec:
  type: NodePort
  ports:
  - port: 1030
    targetPort:
    nodePort:
  selector:
    app: f4i-murcia-parkingsite
