apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: f4i-tv-facerecognition
spec:
  selector:
    matchLabels:
      app: f4i-facerecognition
  replicas: 1
  template:
    metadata:
      labels:
        app: f4i-facerecognition
    spec:
      containers:
      - name: f4i-facerecognition
        image: fed4iot/facerecognition-tv:latest
        ports:
        - containerPort: 5000 
      - name: mongo-for-facerecognition
        image: mongo:latest
      - name: f4i-http-sidecar
        image: fed4iot/http-sidecar-tv:latest
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: f4i-facerecognition-tv-svc
  labels:
    app: f4i-facerecognition
spec:
  type: NodePort
  selector:
    app: f4i-facerecognition
  ports:
  - port: 5000
    nodePort:
    name: port5000 
  - port: 80
    nodePort:
    targetPort: 5001
    name: http
