apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: f4i-tv-generic-multi-vthing
spec:
  selector:
    matchLabels:
      app: f4i-generic-multi-vthing
  replicas: 1
  template:
    metadata:
      labels:
        app: f4i-generic-multi-vthing
    spec:
      containers:
      - name: f4i-generic-multi-vthing
        image: fed4iot/generic-multi-vthing-tv:latest
        ports:
        - containerPort: 5000 
      - name: mongo-for-generic-multi-vthing
        image: mongo:latest
      - name: f4i-http-sidecar
        image: fed4iot/http-sidecar-tv:latest
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: f4i-generic-multi-vthing-tv-svc
  labels:
    app: f4i-generic-multi-vthing
spec:
  type: NodePort
  selector:
    app: f4i-generic-multi-vthing
  ports:
  - port: 5000
    nodePort: 32040
    name: port5000 
  - port: 80
    nodePort: 31299
    targetPort: 5001
    name: http
